In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[20,16,20],[8,10,10]])

In [4]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [  4,  20,  20],
       [  4,   8,  10]])

In [5]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [6]:
price_per_unit*units #Here numpy use broadcasting and expands the price_oer_unit data with the same rows and covert a 3*3 2D matrix so its not right answer what i want

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [9]:
price_per_unit = np.array([[1000,400,1200],[1000,400,1200],[1000,400,1200]])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [10]:
price_per_unit*units # Look both gave the same answer

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [8]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])